# Generated by Django 5.0.6 on 2024-07-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=150)),
                ("capacity", models.PositiveIntegerField()),
                ("photos", models.ManyToManyField(blank=True, to="media.photo")),
                ("videos", models.ManyToManyField(blank=True, to="media.video")),
            ],
        ),
    ]
