# Generated by Django 5.0.6 on 2024-07-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
