# Generated by Django 5.0.6 on 2024-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("shelter", "0002_shelter_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="photos",
            field=models.ManyToManyField(blank=True, null=True, to="media.photo"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="videos",
            field=models.ManyToManyField(blank=True, null=True, to="media.video"),
        ),
    ]
