# Generated by Django 5.0.6 on 2024-07-03 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0003_shelter_photos_shelter_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelter",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="videos",
        ),
    ]
