# Generated by Django 5.0.6 on 2024-06-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
