# Generated by Django 5.0.1 on 2024-06-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.user'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pet.pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photos',
            field=models.ManyToManyField(to='pet.photo'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pet.shelter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.shelter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='videos',
            field=models.ManyToManyField(to='pet.video'),
        ),
    ]
