# Generated by Django 5.0.6 on 2024-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="home_environment",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="previous_pet_experience",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="reason_for_adoption",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
