# Generated by Django 5.0.6 on 2024-07-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0004_alter_review_shelter_alter_pet_shelter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="photos",
            field=models.ManyToManyField(blank=True, null=True, to="pet.photo"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="videos",
            field=models.ManyToManyField(blank=True, null=True, to="pet.video"),
        ),
    ]
