# Generated by Django 5.0.6 on 2024-07-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0006_pet_pet_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.breed"
            ),
        ),
        migrations.AddField(
            model_name="breed",
            name="pet_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeds",
                to="pet.pettype",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="pet_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.pettype"
            ),
        ),
    ]
