# Generated by Django 5.0.6 on 2024-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("pet", "0007_breed_pettype_alter_pet_breed_breed_pet_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="photos",
            field=models.ManyToManyField(blank=True, to="media.photo"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="videos",
            field=models.ManyToManyField(blank=True, to="media.video"),
        ),
    ]
