# Generated by Django 5.0.6 on 2024-07-03 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0010_remove_pet_photos_remove_pet_videos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
